# Generated by Django 5.0.6 on 2024-07-09 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_controller_app', '0002_alter_usertransaction_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertransaction',
            name='amount',
            field=models.FloatField(),
        ),
    ]
