# Generated by Django 5.0.6 on 2024-07-17 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_controller_app', '0003_alter_usertransaction_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertransaction',
            name='created_category_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_transactions', to='budget_controller_app.user'),
        ),
        migrations.AlterField(
            model_name='usertransaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='budget_controller_app.user'),
        ),
    ]
