# Generated by Django 5.0.7 on 2024-07-31 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_controller_app', '0007_user_is_active_user_is_staff_user_is_superuser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.IntegerField(max_length=15, unique=True),
        ),
    ]
